spring:
  application:
    name: app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 10
        format_sql: true

  profiles:
    active: development