spring:
  application:
    name: app

  profiles:
    active: development

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 10
        format_sql: true
        use_sql_comments: true


logging:
  level:
    root: INFO