spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false


logging:
  level:
    org.hibernate: ERROR
    org.springframework.orm.jpa: WARN
